gemini.api.key=${GEMINI_API_KEY}
gemini.api.base-url=https://generativelanguage.googleapis.com
gemini.api.model=gemini-flash-latest

#postgresql://neondb_owner:npg_VH4JkoX5wjif@ep-square-thunder-at5sweaw.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
# 15 mins
jwt.expiration-ms=900000 
# 7 days
jwt.refresh-expiration-ms=604800000  

pagination.default-page-size=20
pagination.max-page-size=100
pagination.default-sort-parameter=createdAt
pagination.default-sorting-order=descending

#
#logging.file.name=logs/app.log
#logging.level.com.laxmannath.job_scraper_backend=INFO

spring.rabbitmq.addresses=${RABBITMQ_URL}

spring.rabbitmq.ssl.enabled=true



mailjet.api.key=${MAILJET_API_KEY}
mailjet.secret.key=${MAILJET_SECRET_KEY}
app.from-email=${APP_FROM_EMAIL}

app.frontend-url=${FRONTEND_URL:http://localhost:3000}

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit.listener=DEBUG




spring.data.redis.url=${REDIS_URL}
spring.data.redis.timeout=2000ms
spring.data.redis.connect-timeout=2000ms
