name: Backend CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'job-scraper-backend/**'
      - '.github/workflows/backend-ci.yml'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'job-scraper-backend/**'

jobs:
  backend:
    name: Build Spring Boot
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: job-scraper-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw clean verify
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}